import type { ProjectItemProps } from "../types/projects";

export const PROJECT_CONTENTS: ProjectItemProps[] = [
	{
		title: "E-Commerce Platform",
		slug: "ecommerce-platform",
		description: "A modern e-commerce platform built with React and Node.js",
		image: "/images/projects/ecommerce-platform.svg",
		link_demo: "https://demo.example.com",
		link_github: "https://github.com/example/ecommerce",
		stacks: '["React", "Node.js", "MongoDB", "TypeScript"]',
		content: "ecommerce-platform.mdx",
		is_show: true,
		is_featured: true,
		updated_at: new Date("2024-01-15"),
	},
	{
		title: "Task Management App",
		slug: "task-management",
		description: "A collaborative task management application",
		image: "/images/projects/task-management.svg",
		link_demo: "https://tasks.example.com",
		link_github: "https://github.com/example/tasks",
		stacks: '["Vue.js", "Express", "PostgreSQL"]',
		content: "task-management.mdx",
		is_show: true,
		is_featured: false,
		updated_at: new Date("2024-01-10"),
	},
	{
		title: "Weather Dashboard",
		slug: "weather-dashboard",
		description: "A responsive weather forecasting dashboard",
		image: "/images/projects/weather-dashboard.svg",
		link_demo: "https://weather.example.com",
		link_github: "https://github.com/example/weather",
		stacks: '["React", "TypeScript", "Weather API"]',
		content: "weather-dashboard.mdx",
		is_show: true,
		is_featured: true,
		updated_at: new Date("2024-01-20"),
	},
	{
		title: "Blog Platform",
		slug: "blog-platform",
		description: "A modern blogging platform with markdown support",
		image: "/images/projects/blog-platform.svg",
		link_demo: "https://blog.example.com",
		link_github: "https://github.com/example/blog",
		stacks: '["Next.js", "Prisma", "PostgreSQL"]',
		content: "blog-platform.mdx",
		is_show: false,
		is_featured: false,
		updated_at: new Date("2024-01-05"),
	},
];
